#include "stdafx.h"
#include "AssignmentField.h"
#include "LocaleData.h"
//#include "GarbageCollector.h"

class AssignmentFieldExt : public FieldType
{
public:
	AssignmentFieldExt(int value, DataType type, FieldType* unitsType = NULL)
	{
		_value = value;
		_datatype = type;
		_fieldtype = unitsType;
	}
	~AssignmentFieldExt() 
	{
		
	}

	virtual int getValue()
	{
		return _value;
	}

	virtual DataType getDataType()
	{
		return _datatype;
	}

	virtual FieldType* getUnitsType()
	{
		return _fieldtype;
	}

	virtual CString getName(Locale* locale)
	{
		if (_value > AF_START && _value < AF_FINISH)
			return LocaleData::getColumnText(locale, LocaleData::ASSIGNMENT_COLUMNS, _value);
		else
			return L"";
	}

private:
	int _value;
	DataType _datatype;
	FieldType* _fieldtype;
};

static std::auto_ptr<AssignmentFieldExt> _AssignmentFields[AF_FINISH + 1];	// 600
void ResetAFieldExt(AssignmentField field, DataType type, FieldType* unitsType = NULL)
{
	_AssignmentFields[field].reset(new AssignmentFieldExt(field, type, unitsType));
}

/**
* Instances of this type represent Assignment fields.
*/
void InstanceAllAssignmentField()
{
	ResetAFieldExt(AF_START, DataType::DT_DATE); // Must always be first value

	ResetAFieldExt(AF_DURATION1_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION2_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION3_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION4_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION5_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION6_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION7_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION8_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION9_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_DURATION10_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_ACTUAL_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ACTUAL_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ASSIGNMENT_DELAY, DataType::DT_DELAY);
	ResetAFieldExt(AF_VARIABLE_RATE_UNITS, DataType::DT_WORK_UNITS);
	ResetAFieldExt(AF_ASSIGNMENT_UNITS, DataType::DT_UNITS);
	ResetAFieldExt(AF_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE_START, DataType::DT_DATE);
	ResetAFieldExt(AF_ACTUAL_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_ACTUAL_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_OVERTIME_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_WORK_CONTOUR, DataType::DT_STRING);
	ResetAFieldExt(AF_REMAINING_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_LEVELING_DELAY_UNITS, DataType::DT_TIME_UNITS);
	ResetAFieldExt(AF_LEVELING_DELAY, DataType::DT_DURATION, _AssignmentFields[AF_LEVELING_DELAY_UNITS].get());
	ResetAFieldExt(AF_UNIQUE_ID, DataType::DT_INTEGER);
	ResetAFieldExt(AF_TASK_UNIQUE_ID, DataType::DT_INTEGER);
	ResetAFieldExt(AF_RESOURCE_UNIQUE_ID, DataType::DT_INTEGER);
	ResetAFieldExt(AF_TIMEPHASED_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_ACTUAL_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_ACTUAL_OVERTIME_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE1_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE2_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE3_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE4_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE5_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE6_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE7_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE8_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE9_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE10_WORK, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE1_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE2_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE3_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE4_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE5_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE6_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE7_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE8_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE9_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TIMEPHASED_BASELINE10_COST, DataType::DT_BINARY);
	ResetAFieldExt(AF_TASK_ID, DataType::DT_INTEGER);
	ResetAFieldExt(AF_RESOURCE_ID, DataType::DT_INTEGER);
	ResetAFieldExt(AF_TASK_NAME, DataType::DT_STRING);
	ResetAFieldExt(AF_RESOURCE_NAME, DataType::DT_STRING);
	ResetAFieldExt(AF_REGULAR_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_ACTUAL_OVERTIME_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_REMAINING_OVERTIME_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_PEAK, DataType::DT_UNITS);
	ResetAFieldExt(AF_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_REMAINING_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ACTUAL_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_REMAINING_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BCWS, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BCWP, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ACWP, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_SV, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST_VARIANCE, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_PERCENT_WORK_COMPLETE, DataType::DT_PERCENTAGE);
	ResetAFieldExt(AF_PROJECT, DataType::DT_STRING);
	ResetAFieldExt(AF_NOTES, DataType::DT_ASCII_STRING);
	ResetAFieldExt(AF_CONFIRMED, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_RESPONSE_PENDING, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_UPDATE_NEEDED, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_TEAM_STATUS_PENDING, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_COST_RATE_TABLE, DataType::DT_SHORT);
	ResetAFieldExt(AF_TEXT1, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT2, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT3, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT4, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT5, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT6, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT7, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT8, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT9, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT10, DataType::DT_STRING);
	ResetAFieldExt(AF_START1, DataType::DT_DATE);
	ResetAFieldExt(AF_START2, DataType::DT_DATE);
	ResetAFieldExt(AF_START3, DataType::DT_DATE);
	ResetAFieldExt(AF_START4, DataType::DT_DATE);
	ResetAFieldExt(AF_START5, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH1, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH2, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH3, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH4, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH5, DataType::DT_DATE);
	ResetAFieldExt(AF_NUMBER1, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER2, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER3, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER4, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER5, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_DURATION1, DataType::DT_DURATION, _AssignmentFields[AF_DURATION1_UNITS].get());
	ResetAFieldExt(AF_DURATION2, DataType::DT_DURATION, _AssignmentFields[AF_DURATION2_UNITS].get());
	ResetAFieldExt(AF_DURATION3, DataType::DT_DURATION, _AssignmentFields[AF_DURATION3_UNITS].get());
	ResetAFieldExt(AF_COST1, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST2, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST3, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_FLAG10, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG1, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG2, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG3, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG4, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG5, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG6, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG7, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG8, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG9, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_LINKED_FIELDS, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_OVERALLOCATED, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_TASK_SUMMARY_NAME, DataType::DT_STRING);
	ResetAFieldExt(AF_HYPERLINK, DataType::DT_STRING);
	ResetAFieldExt(AF_HYPERLINK_ADDRESS, DataType::DT_STRING);
	ResetAFieldExt(AF_HYPERLINK_SUBADDRESS, DataType::DT_STRING);
	ResetAFieldExt(AF_HYPERLINK_HREF, DataType::DT_STRING);
	ResetAFieldExt(AF_COST4, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST5, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST6, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST7, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST8, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST9, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_COST10, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_DATE1, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE2, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE3, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE4, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE5, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE6, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE7, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE8, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE9, DataType::DT_DATE);
	ResetAFieldExt(AF_DATE10, DataType::DT_DATE);
	ResetAFieldExt(AF_DURATION4, DataType::DT_DURATION, _AssignmentFields[AF_DURATION4_UNITS].get());
	ResetAFieldExt(AF_DURATION5, DataType::DT_DURATION, _AssignmentFields[AF_DURATION5_UNITS].get());
	ResetAFieldExt(AF_DURATION6, DataType::DT_DURATION, _AssignmentFields[AF_DURATION6_UNITS].get());
	ResetAFieldExt(AF_DURATION7, DataType::DT_DURATION, _AssignmentFields[AF_DURATION7_UNITS].get());
	ResetAFieldExt(AF_DURATION8, DataType::DT_DURATION, _AssignmentFields[AF_DURATION8_UNITS].get());
	ResetAFieldExt(AF_DURATION9, DataType::DT_DURATION, _AssignmentFields[AF_DURATION9_UNITS].get());
	ResetAFieldExt(AF_DURATION10, DataType::DT_DURATION, _AssignmentFields[AF_DURATION10_UNITS].get());
	ResetAFieldExt(AF_FINISH6, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH7, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH8, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH9, DataType::DT_DATE);
	ResetAFieldExt(AF_FINISH10, DataType::DT_DATE);
	ResetAFieldExt(AF_FLAG11, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG12, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG13, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG14, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG15, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG16, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG17, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG18, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG19, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_FLAG20, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_NUMBER6, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER7, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER8, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER9, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER10, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER11, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER12, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER13, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER14, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER15, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER16, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER17, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER18, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER19, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_NUMBER20, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_START6, DataType::DT_DATE);
	ResetAFieldExt(AF_START7, DataType::DT_DATE);
	ResetAFieldExt(AF_START8, DataType::DT_DATE);
	ResetAFieldExt(AF_START9, DataType::DT_DATE);
	ResetAFieldExt(AF_START10, DataType::DT_DATE);
	ResetAFieldExt(AF_TEXT11, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT12, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT13, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT14, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT15, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT16, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT17, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT18, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT19, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT20, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT21, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT22, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT23, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT24, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT25, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT26, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT27, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT28, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT29, DataType::DT_STRING);
	ResetAFieldExt(AF_TEXT30, DataType::DT_STRING);
	ResetAFieldExt(AF_INDEX, DataType::DT_INTEGER);
	ResetAFieldExt(AF_CV, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_WORK_VARIANCE, DataType::DT_WORK);
	ResetAFieldExt(AF_START_VARIANCE, DataType::DT_DURATION);
	ResetAFieldExt(AF_FINISH_VARIANCE, DataType::DT_DURATION);
	ResetAFieldExt(AF_VAC, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_FIXED_MATERIAL_ASSIGNMENT, DataType::DT_STRING);
	ResetAFieldExt(AF_RESOURCE_TYPE, DataType::DT_RESOURCE_TYPE);
	ResetAFieldExt(AF_HYPERLINK_SCREEN_TIP, DataType::DT_STRING);
	ResetAFieldExt(AF_WBS, DataType::DT_STRING);
	ResetAFieldExt(AF_BASELINE1_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE1_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE1_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE1_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE2_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE2_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE2_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE2_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE3_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE3_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE3_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE3_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE4_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE4_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE4_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE4_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE5_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE5_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE5_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE5_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE6_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE6_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE6_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE6_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE7_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE7_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE7_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE7_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE8_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE8_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE8_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE8_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE9_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE9_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE9_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE9_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE10_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE10_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE10_START, DataType::DT_DATE);
	ResetAFieldExt(AF_BASELINE10_FINISH, DataType::DT_DATE);
	ResetAFieldExt(AF_TASK_OUTLINE_NUMBER, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_COST1, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST2, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST3, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST4, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST5, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST6, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST7, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST8, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST9, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_COST10, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_ENTERPRISE_DATE1, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE2, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE3, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE4, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE5, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE6, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE7, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE8, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE9, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE10, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE11, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE12, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE13, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE14, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE15, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE16, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE17, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE18, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE19, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE20, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE21, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE22, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE23, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE24, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE25, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE26, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE27, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE28, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE29, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DATE30, DataType::DT_DATE);
	ResetAFieldExt(AF_ENTERPRISE_DURATION1, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION2, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION3, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION4, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION5, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION6, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION7, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION8, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION9, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_DURATION10, DataType::DT_DURATION);
	ResetAFieldExt(AF_ENTERPRISE_FLAG1, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG2, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG3, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG4, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG5, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG6, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG7, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG8, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG9, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG10, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG11, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG12, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG13, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG14, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG15, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG16, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG17, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG18, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG19, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_FLAG20, DataType::DT_BOOLEAN);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER1, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER2, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER3, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER4, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER5, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER6, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER7, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER8, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER9, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER10, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER11, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER12, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER13, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER14, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER15, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER16, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER17, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER18, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER19, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER20, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER21, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER22, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER23, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER24, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER25, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER26, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER27, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER28, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER29, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER30, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER31, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER32, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER33, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER34, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER35, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER36, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER37, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER38, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER39, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_NUMBER40, DataType::DT_NUMERIC);
	ResetAFieldExt(AF_ENTERPRISE_TEXT1, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT2, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT3, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT4, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT5, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT6, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT7, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT8, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT9, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT10, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT11, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT12, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT13, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT14, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT15, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT16, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT17, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT18, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT19, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT20, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT21, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT22, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT23, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT24, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT25, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT26, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT27, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT28, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT29, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT30, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT31, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT32, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT33, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT34, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT35, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT36, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT37, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT38, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT39, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEXT40, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE1, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE2, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE3, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE4, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE5, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE6, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE7, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE8, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE9, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE10, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE11, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE12, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE13, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE14, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE15, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE16, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE17, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE18, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE19, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE20, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE21, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE22, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE23, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE24, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE25, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE26, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE27, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE28, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_OUTLINE_CODE29, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_RBS, DataType::DT_STRING);
	ResetAFieldExt(AF_RESOURCE_REQUEST_TYPE, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_TEAM_MEMBER, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE20, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE21, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE22, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE23, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE24, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE25, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE26, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE27, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE28, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_RESOURCE_MULTI_VALUE29, DataType::DT_STRING);
	ResetAFieldExt(AF_ACTUAL_WORK_PROTECTED, DataType::DT_WORK);
	ResetAFieldExt(AF_ACTUAL_OVERTIME_WORK_PROTECTED, DataType::DT_WORK);
	ResetAFieldExt(AF_CREATED, DataType::DT_DATE);
	ResetAFieldExt(AF_GUID, DataType::DT_GUID);
	ResetAFieldExt(AF_ASSIGNMENT_TASK_GUID, DataType::DT_GUID);
	ResetAFieldExt(AF_ASSIGNMENT_RESOURCE_GUID, DataType::DT_GUID);
	ResetAFieldExt(AF_SUMMARY, DataType::DT_STRING);
	ResetAFieldExt(AF_OWNER, DataType::DT_STRING);
	ResetAFieldExt(AF_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE1_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE1_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE2_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE2_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE3_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE3_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE4_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE4_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE5_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE5_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE6_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE6_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE7_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE7_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE8_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE8_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE9_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE9_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_BASELINE10_BUDGET_WORK, DataType::DT_WORK);
	ResetAFieldExt(AF_BASELINE10_BUDGET_COST, DataType::DT_CURRENCY);
	ResetAFieldExt(AF_UNAVAILABLE, DataType::DT_STRING); // Dummy entry
	ResetAFieldExt(AF_HYPERLINK_DATA, DataType::DT_BINARY);

	// KEEP THESE TOGETHER AND IN ORDER
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD1, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD2, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD3, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD4, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD5, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD6, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD7, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD8, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD9, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD10, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD11, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD12, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD13, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD14, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD15, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD16, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD17, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD18, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD19, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD20, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD21, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD22, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD23, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD24, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD25, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD26, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD27, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD28, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD29, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD30, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD31, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD32, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD33, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD34, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD35, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD36, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD37, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD38, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD39, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD40, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD41, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD42, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD43, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD44, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD45, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD46, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD47, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD48, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD49, DataType::DT_STRING);
	ResetAFieldExt(AF_ENTERPRISE_CUSTOM_FIELD50, DataType::DT_STRING);
	// KEEP THESE TOGETHER AND IN ORDER

	ResetAFieldExt(AF_FINISH, DataType::DT_DATE); // Must always be last value
}

FieldType* AssignmentFieldClass::getInstance(int type)
{
	if (_AssignmentFields[AF_FINISH - 1].get() == NULL)
	{
		InstanceAllAssignmentField();
	}

	return _AssignmentFields[type].get();
}