#include "stdafx.h"
#include "TaskField.h"
#include "LocaleData.h"
//#include "GarbageCollector.h"

class TaskFieldExt : public FieldType
{
public:
	TaskFieldExt(int value, DataType type, FieldType* unitsType = NULL)
	{
		_value = value;
		_datatype = type;
		_fieldtype = unitsType;
	}

	virtual int getValue()
	{
		return _value;
	}

	virtual DataType getDataType()
	{
		return _datatype;
	}

	virtual FieldType* getUnitsType()
	{
		return _fieldtype;
	}

	CString getName(Locale* locale)
	{
		if (_value >= TF_START && _value <= TF_FINISH)
			return LocaleData::getColumnText(locale, LocaleData::TASK_COLUMNS, _value);
		else
			return L"";
	}

	CString toString()
	{
		return getName(Locale::getDefault());
	}

private:
	int					_value;
	DataType			_datatype;
	FieldType*	_fieldtype;
};

static std::auto_ptr<TaskFieldExt> _TaskFields[TF_FINISH + 1];	// 600

void ResetTaskField(TaskField field, DataType type, FieldType* unitsType = NULL)
{
	_TaskFields[field].reset(new TaskFieldExt(field, type, unitsType));
}

/**
 * Instances of this type represent Task fields.
 */
void InstanceAllTaskField()
{
	ResetTaskField(TF_START, DataType::DT_DATE); // Must always be first value

	ResetTaskField(TF_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ACTUAL_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_LEVELING_DELAY_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION1_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION2_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION3_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION4_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION5_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION6_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION7_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION8_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION9_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_DURATION10_UNITS, DataType::DT_TIME_UNITS);

	ResetTaskField(TF_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE_WORK, DataType::DT_WORK);
	ResetTaskField(TF_ACTUAL_WORK, DataType::DT_WORK);
	ResetTaskField(TF_WORK_VARIANCE, DataType::DT_DURATION);
	ResetTaskField(TF_REMAINING_WORK, DataType::DT_WORK);
	ResetTaskField(TF_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_ACTUAL_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST_VARIANCE, DataType::DT_CURRENCY);
	ResetTaskField(TF_REMAINING_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BCWP, DataType::DT_CURRENCY);
	ResetTaskField(TF_BCWS, DataType::DT_CURRENCY);
	ResetTaskField(TF_SV, DataType::DT_CURRENCY);
	ResetTaskField(TF_NAME, DataType::DT_STRING);
	ResetTaskField(TF_WBS, DataType::DT_STRING);
	ResetTaskField(TF_CONSTRAINT_TYPE, DataType::DT_CONSTRAINT);
	ResetTaskField(TF_CONSTRAINT_DATE, DataType::DT_DATE);
	ResetTaskField(TF_CRITICAL, DataType::DT_BOOLEAN);
	ResetTaskField(TF_LEVELING_DELAY, DataType::DT_DURATION, _TaskFields[TF_LEVELING_DELAY_UNITS].get());
	ResetTaskField(TF_FREE_SLACK, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_TOTAL_SLACK, DataType::DT_DURATION);
	ResetTaskField(TF_ID, DataType::DT_INTEGER);
	ResetTaskField(TF_MILESTONE, DataType::DT_BOOLEAN);
	ResetTaskField(TF_PRIORITY, DataType::DT_PRIORITY);
	ResetTaskField(TF_SUBPROJECT_FILE, DataType::DT_STRING);
	ResetTaskField(TF_BASELINE_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE_DURATION_UNITS].get());
	ResetTaskField(TF_ACTUAL_DURATION, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_DURATION, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_DURATION_VARIANCE, DataType::DT_DURATION);
	ResetTaskField(TF_REMAINING_DURATION, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_PERCENT_COMPLETE, DataType::DT_PERCENTAGE);
	ResetTaskField(TF_PERCENT_WORK_COMPLETE, DataType::DT_PERCENTAGE);
	ResetTaskField(TF_EARLY_START, DataType::DT_DATE);
	ResetTaskField(TF_EARLY_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_LATE_START, DataType::DT_DATE);
	ResetTaskField(TF_LATE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_ACTUAL_START, DataType::DT_DATE);
	ResetTaskField(TF_ACTUAL_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_START_VARIANCE, DataType::DT_DURATION);
	ResetTaskField(TF_FINISH_VARIANCE, DataType::DT_DURATION);
	ResetTaskField(TF_PREDECESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_SUCCESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_RESOURCE_NAMES, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_INITIALS, DataType::DT_STRING);
	ResetTaskField(TF_TEXT1, DataType::DT_STRING);
	ResetTaskField(TF_START1, DataType::DT_DATE);
	ResetTaskField(TF_FINISH1, DataType::DT_DATE);
	ResetTaskField(TF_TEXT2, DataType::DT_STRING);
	ResetTaskField(TF_START2, DataType::DT_DATE);
	ResetTaskField(TF_FINISH2, DataType::DT_DATE);
	ResetTaskField(TF_TEXT3, DataType::DT_STRING);
	ResetTaskField(TF_START3, DataType::DT_DATE);
	ResetTaskField(TF_FINISH3, DataType::DT_DATE);
	ResetTaskField(TF_TEXT4, DataType::DT_STRING);
	ResetTaskField(TF_START4, DataType::DT_DATE);
	ResetTaskField(TF_FINISH4, DataType::DT_DATE);
	ResetTaskField(TF_TEXT5, DataType::DT_STRING);
	ResetTaskField(TF_START5, DataType::DT_DATE);
	ResetTaskField(TF_FINISH5, DataType::DT_DATE);
	ResetTaskField(TF_TEXT6, DataType::DT_STRING);
	ResetTaskField(TF_TEXT7, DataType::DT_STRING);
	ResetTaskField(TF_TEXT8, DataType::DT_STRING);
	ResetTaskField(TF_TEXT9, DataType::DT_STRING);
	ResetTaskField(TF_TEXT10, DataType::DT_STRING);
	ResetTaskField(TF_MARKED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG1, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG2, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG3, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG4, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG5, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG6, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG7, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG8, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG9, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG10, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ROLLUP, DataType::DT_BOOLEAN);
	ResetTaskField(TF_CV, DataType::DT_NUMERIC);
	ResetTaskField(TF_PROJECT, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_LEVEL, DataType::DT_SHORT);
	ResetTaskField(TF_UNIQUE_ID, DataType::DT_INTEGER);
	ResetTaskField(TF_NUMBER1, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER2, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER3, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER4, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER5, DataType::DT_NUMERIC);
	ResetTaskField(TF_SUMMARY, DataType::DT_BOOLEAN);
	ResetTaskField(TF_CREATED, DataType::DT_DATE);
	ResetTaskField(TF_NOTES, DataType::DT_ASCII_STRING);
	ResetTaskField(TF_UNIQUE_ID_PREDECESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_UNIQUE_ID_SUCCESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_OBJECTS, DataType::DT_NUMERIC);
	ResetTaskField(TF_LINKED_FIELDS, DataType::DT_BOOLEAN);
	ResetTaskField(TF_RESUME, DataType::DT_DATE);
	ResetTaskField(TF_STOP, DataType::DT_DATE);
	ResetTaskField(TF_OUTLINE_NUMBER, DataType::DT_STRING);
	ResetTaskField(TF_DURATION1, DataType::DT_DURATION, _TaskFields[TF_DURATION1_UNITS].get());
	ResetTaskField(TF_DURATION2, DataType::DT_DURATION, _TaskFields[TF_DURATION2_UNITS].get());
	ResetTaskField(TF_DURATION3, DataType::DT_DURATION, _TaskFields[TF_DURATION3_UNITS].get());
	ResetTaskField(TF_COST1, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST2, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST3, DataType::DT_CURRENCY);
	ResetTaskField(TF_HIDE_BAR, DataType::DT_BOOLEAN);
	ResetTaskField(TF_CONFIRMED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_UPDATE_NEEDED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_CONTACT, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_GROUP, DataType::DT_STRING);
	ResetTaskField(TF_ACWP, DataType::DT_NUMERIC);
	ResetTaskField(TF_TYPE, DataType::DT_TASK_TYPE);
	ResetTaskField(TF_RECURRING, DataType::DT_BOOLEAN);
	ResetTaskField(TF_EFFORT_DRIVEN, DataType::DT_BOOLEAN);
	ResetTaskField(TF_OVERTIME_WORK, DataType::DT_DURATION);
	ResetTaskField(TF_ACTUAL_OVERTIME_WORK, DataType::DT_WORK);
	ResetTaskField(TF_REMAINING_OVERTIME_WORK, DataType::DT_WORK);
	ResetTaskField(TF_REGULAR_WORK, DataType::DT_DURATION);
	ResetTaskField(TF_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_ACTUAL_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_REMAINING_OVERTIME_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_INDICATORS, DataType::DT_STRING);
	ResetTaskField(TF_HYPERLINK, DataType::DT_STRING);
	ResetTaskField(TF_HYPERLINK_ADDRESS, DataType::DT_STRING);
	ResetTaskField(TF_HYPERLINK_SUBADDRESS, DataType::DT_STRING);
	ResetTaskField(TF_HYPERLINK_HREF, DataType::DT_STRING);
	ResetTaskField(TF_ASSIGNMENT, DataType::DT_STRING);
	ResetTaskField(TF_OVERALLOCATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_EXTERNAL_TASK, DataType::DT_BOOLEAN);
	ResetTaskField(TF_SUBPROJECT_READ_ONLY, DataType::DT_BOOLEAN);
	ResetTaskField(TF_RESPONSE_PENDING, DataType::DT_BOOLEAN);
	ResetTaskField(TF_TEAMSTATUS_PENDING, DataType::DT_BOOLEAN);
	ResetTaskField(TF_LEVELING_CAN_SPLIT, DataType::DT_BOOLEAN);
	ResetTaskField(TF_LEVEL_ASSIGNMENTS, DataType::DT_BOOLEAN);
	ResetTaskField(TF_WORK_CONTOUR, DataType::DT_STRING);
	ResetTaskField(TF_COST4, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST5, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST6, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST7, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST8, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST9, DataType::DT_CURRENCY);
	ResetTaskField(TF_COST10, DataType::DT_CURRENCY);
	ResetTaskField(TF_DATE1, DataType::DT_DATE);
	ResetTaskField(TF_DATE2, DataType::DT_DATE);
	ResetTaskField(TF_DATE3, DataType::DT_DATE);
	ResetTaskField(TF_DATE4, DataType::DT_DATE);
	ResetTaskField(TF_DATE5, DataType::DT_DATE);
	ResetTaskField(TF_DATE6, DataType::DT_DATE);
	ResetTaskField(TF_DATE7, DataType::DT_DATE);
	ResetTaskField(TF_DATE8, DataType::DT_DATE);
	ResetTaskField(TF_DATE9, DataType::DT_DATE);
	ResetTaskField(TF_DATE10, DataType::DT_DATE);
	ResetTaskField(TF_DURATION4, DataType::DT_DURATION, _TaskFields[TF_DURATION4_UNITS].get());
	ResetTaskField(TF_DURATION5, DataType::DT_DURATION, _TaskFields[TF_DURATION5_UNITS].get());
	ResetTaskField(TF_DURATION6, DataType::DT_DURATION, _TaskFields[TF_DURATION6_UNITS].get());
	ResetTaskField(TF_DURATION7, DataType::DT_DURATION, _TaskFields[TF_DURATION7_UNITS].get());
	ResetTaskField(TF_DURATION8, DataType::DT_DURATION, _TaskFields[TF_DURATION8_UNITS].get());
	ResetTaskField(TF_DURATION9, DataType::DT_DURATION, _TaskFields[TF_DURATION9_UNITS].get());
	ResetTaskField(TF_DURATION10, DataType::DT_DURATION, _TaskFields[TF_DURATION10_UNITS].get());
	ResetTaskField(TF_START6, DataType::DT_DATE);
	ResetTaskField(TF_FINISH6, DataType::DT_DATE);
	ResetTaskField(TF_START7, DataType::DT_DATE);
	ResetTaskField(TF_FINISH7, DataType::DT_DATE);
	ResetTaskField(TF_START8, DataType::DT_DATE);
	ResetTaskField(TF_FINISH8, DataType::DT_DATE);
	ResetTaskField(TF_START9, DataType::DT_DATE);
	ResetTaskField(TF_FINISH9, DataType::DT_DATE);
	ResetTaskField(TF_START10, DataType::DT_DATE);
	ResetTaskField(TF_FINISH10, DataType::DT_DATE);
	ResetTaskField(TF_FLAG11, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG12, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG13, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG14, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG15, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG16, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG17, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG18, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG19, DataType::DT_BOOLEAN);
	ResetTaskField(TF_FLAG20, DataType::DT_BOOLEAN);
	ResetTaskField(TF_NUMBER6, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER7, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER8, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER9, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER10, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER11, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER12, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER13, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER14, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER15, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER16, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER17, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER18, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER19, DataType::DT_NUMERIC);
	ResetTaskField(TF_NUMBER20, DataType::DT_NUMERIC);
	ResetTaskField(TF_TEXT11, DataType::DT_STRING);
	ResetTaskField(TF_TEXT12, DataType::DT_STRING);
	ResetTaskField(TF_TEXT13, DataType::DT_STRING);
	ResetTaskField(TF_TEXT14, DataType::DT_STRING);
	ResetTaskField(TF_TEXT15, DataType::DT_STRING);
	ResetTaskField(TF_TEXT16, DataType::DT_STRING);
	ResetTaskField(TF_TEXT17, DataType::DT_STRING);
	ResetTaskField(TF_TEXT18, DataType::DT_STRING);
	ResetTaskField(TF_TEXT19, DataType::DT_STRING);
	ResetTaskField(TF_TEXT20, DataType::DT_STRING);
	ResetTaskField(TF_TEXT21, DataType::DT_STRING);
	ResetTaskField(TF_TEXT22, DataType::DT_STRING);
	ResetTaskField(TF_TEXT23, DataType::DT_STRING);
	ResetTaskField(TF_TEXT24, DataType::DT_STRING);
	ResetTaskField(TF_TEXT25, DataType::DT_STRING);
	ResetTaskField(TF_TEXT26, DataType::DT_STRING);
	ResetTaskField(TF_TEXT27, DataType::DT_STRING);
	ResetTaskField(TF_TEXT28, DataType::DT_STRING);
	ResetTaskField(TF_TEXT29, DataType::DT_STRING);
	ResetTaskField(TF_TEXT30, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_PHONETICS, DataType::DT_STRING);
	ResetTaskField(TF_ASSIGNMENT_DELAY, DataType::DT_STRING);
	ResetTaskField(TF_ASSIGNMENT_UNITS, DataType::DT_STRING);
	ResetTaskField(TF_COST_RATE_TABLE, DataType::DT_STRING);
	ResetTaskField(TF_PRELEVELED_START, DataType::DT_DATE);
	ResetTaskField(TF_PRELEVELED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_IGNORE_RESOURCE_CALENDAR, DataType::DT_BOOLEAN);
	ResetTaskField(TF_CALENDAR, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE1, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE2, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE3, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE4, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE5, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE6, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE7, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE8, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE9, DataType::DT_STRING);
	ResetTaskField(TF_OUTLINE_CODE10, DataType::DT_STRING);
	ResetTaskField(TF_DEADLINE, DataType::DT_DATE);
	ResetTaskField(TF_START_SLACK, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_FINISH_SLACK, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_VAC, DataType::DT_NUMERIC);
	ResetTaskField(TF_GROUP_BY_SUMMARY, DataType::DT_STRING);
	ResetTaskField(TF_WBS_PREDECESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_WBS_SUCCESSORS, DataType::DT_RELATION_LIST);
	ResetTaskField(TF_RESOURCE_TYPE, DataType::DT_STRING);
	ResetTaskField(TF_BASELINE1_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE2_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE3_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE4_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE5_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE6_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE7_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE8_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE9_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE10_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_BASELINE1_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE1_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE1_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE1_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE1_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE1_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE2_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE2_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE2_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE2_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE2_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE2_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE3_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE3_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE3_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE3_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE3_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE3_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE4_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE4_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE4_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE4_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE4_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE4_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE5_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE5_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE5_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE5_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE5_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE5_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE6_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE6_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE6_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE6_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE6_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE6_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE7_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE7_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE7_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE7_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE7_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE7_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE8_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE8_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE8_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE8_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE8_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE8_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE9_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE9_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE9_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE9_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE9_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE9_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE10_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE10_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE10_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE10_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE10_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE10_DURATION_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_COST1, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST2, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST3, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST4, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST5, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST6, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST7, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST8, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST9, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_COST10, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_DATE1, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE2, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE3, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE4, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE5, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE6, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE7, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE8, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE9, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE10, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE11, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE12, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE13, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE14, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE15, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE16, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE17, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE18, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE19, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE20, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE21, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE22, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE23, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE24, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE25, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE26, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE27, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE28, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE29, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DATE30, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_DURATION1_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION2_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION3_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION4_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION5_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION6_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION7_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION8_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION9_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION10_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_ENTERPRISE_DURATION1, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION1_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION2, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION2_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION3, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION3_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION4, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION4_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION5, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION5_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION6, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION6_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION7, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION7_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION8, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION8_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION9, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION9_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_DURATION10, DataType::DT_DURATION, _TaskFields[TF_ENTERPRISE_DURATION10_UNITS].get());
	ResetTaskField(TF_ENTERPRISE_FLAG1, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG2, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG3, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG4, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG5, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG6, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG7, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG8, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG9, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG10, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG11, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG12, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG13, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG14, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG15, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG16, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG17, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG18, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG19, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_FLAG20, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_NUMBER1, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER2, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER3, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER4, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER5, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER6, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER7, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER8, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER9, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER10, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER11, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER12, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER13, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER14, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER15, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER16, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER17, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER18, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER19, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER20, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER21, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER22, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER23, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER24, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER25, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER26, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER27, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER28, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER29, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER30, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER31, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER32, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER33, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER34, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER35, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER36, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER37, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER38, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER39, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_NUMBER40, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_TEXT1, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT2, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT3, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT4, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT5, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT6, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT7, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT8, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT9, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT10, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT11, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT12, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT13, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT14, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT15, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT16, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT17, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT18, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT19, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT20, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT21, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT22, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT23, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT24, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT25, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT26, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT27, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT28, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT29, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT30, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT31, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT32, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT33, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT34, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT35, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT36, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT37, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT38, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT39, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_TEXT40, DataType::DT_STRING);
	ResetTaskField(TF_COMPLETE_THROUGH, DataType::DT_DATE);
	ResetTaskField(TF_SUMMARY_PROGRESS, DataType::DT_DATE);
	ResetTaskField(TF_GUID, DataType::DT_GUID);

	ResetTaskField(TF_ACTIVE, DataType::DT_BOOLEAN);
	ResetTaskField(TF_TASK_MODE, DataType::DT_BOOLEAN);

	ResetTaskField(TF_ASSIGNMENT_OWNER, DataType::DT_STRING);
	ResetTaskField(TF_BASELINE_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE_BUDGET_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BASELINE_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_DELIVERABLE_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);

	ResetTaskField(TF_BASELINE1_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE1_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE1_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE1_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE1_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE1_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE1_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE1_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE1_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE1_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE2_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE2_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE2_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE2_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE2_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE2_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE2_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE2_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE2_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE2_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE3_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE3_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE3_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE3_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE3_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE3_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE3_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE3_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE3_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE3_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE4_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE4_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE4_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE4_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE4_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE4_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE4_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE4_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE4_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE4_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE5_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE5_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE5_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE5_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE5_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE5_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE5_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE5_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE5_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE5_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE6_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE6_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE6_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE6_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE6_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE6_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE6_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE6_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE6_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE6_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE7_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE7_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE7_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE7_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE7_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE7_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE7_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE7_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE7_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE7_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE8_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE8_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE8_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE8_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE8_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE8_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE8_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE8_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE8_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE8_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE9_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE9_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE9_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE9_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE9_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE9_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE9_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE9_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE9_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE9_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_BASELINE10_ESTIMATED_START, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE10_ESTIMATED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE10_ESTIMATED_DURATION, DataType::DT_DURATION, _TaskFields[TF_BASELINE10_DURATION_UNITS].get());
	ResetTaskField(TF_BASELINE10_FIXED_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE10_FIXED_COST_ACCRUAL, DataType::DT_ACCRUE);
	ResetTaskField(TF_BASELINE10_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE10_BUDGET_WORK, DataType::DT_CURRENCY);
	ResetTaskField(TF_BASELINE10_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_BASELINE10_DELIVERABLE_START, DataType::DT_DATE);

	ResetTaskField(TF_CPI, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_CVPERCENT, DataType::DT_PERCENTAGE);
	ResetTaskField(TF_DELIVERABLE_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_DELIVERABLE_GUID, DataType::DT_GUID);
	ResetTaskField(TF_DELIVERABLE_NAME, DataType::DT_STRING);
	ResetTaskField(TF_DELIVERABLE_START, DataType::DT_DATE);
	ResetTaskField(TF_DELIVERABLE_TYPE, DataType::DT_STRING); // Check data type

	ResetTaskField(TF_EAC, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_EARNED_VALUE_METHOD, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_ERROR_MESSAGE, DataType::DT_STRING);

	ResetTaskField(TF_IGNORE_WARNINGS, DataType::DT_BOOLEAN);
	ResetTaskField(TF_PEAK, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_PHYSICAL_PERCENT_COMPLETE, DataType::DT_SHORT);
	ResetTaskField(TF_PLACEHOLDER, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_PUBLISH, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_REQUEST_DEMAND, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_SCHEDULED_DURATION, DataType::DT_DURATION, _TaskFields[TF_ACTUAL_DURATION_UNITS].get());
	ResetTaskField(TF_SCHEDULED_FINISH, DataType::DT_DATE);
	ResetTaskField(TF_SCHEDULED_START, DataType::DT_DATE);
	ResetTaskField(TF_SPI, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_STATUS, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_STATUS_INDICATOR, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_STATUS_MANAGER, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_SVPERCENT, DataType::DT_PERCENTAGE);
	ResetTaskField(TF_TASK_CALENDAR, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_TASK_CALENDAR_GUID, DataType::DT_GUID);
	ResetTaskField(TF_TCPI, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_WARNING, DataType::DT_STRING); // Check data type
	ResetTaskField(TF_UNAVAILABLE, DataType::DT_STRING); // Dummy entry

	ResetTaskField(TF_START_TEXT, DataType::DT_STRING);
	ResetTaskField(TF_FINISH_TEXT, DataType::DT_STRING);
	ResetTaskField(TF_DURATION_TEXT, DataType::DT_STRING);
	ResetTaskField(TF_MANUAL_DURATION_UNITS, DataType::DT_TIME_UNITS);
	ResetTaskField(TF_MANUAL_DURATION, DataType::DT_DURATION, _TaskFields[TF_MANUAL_DURATION_UNITS].get());
	ResetTaskField(TF_SUBPROJECT_TASKS_UNIQUEID_OFFSET, DataType::DT_INTEGER);
	ResetTaskField(TF_SUBPROJECT_UNIQUE_TASK_ID, DataType::DT_INTEGER);
	ResetTaskField(TF_SUBPROJECT_TASK_ID, DataType::DT_INTEGER);
	ResetTaskField(TF_HYPERLINK_DATA, DataType::DT_BINARY);
	ResetTaskField(TF_RECURRING_DATA, DataType::DT_BINARY);
	ResetTaskField(TF_OUTLINE_CODE1_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE2_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE3_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE4_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE5_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE6_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE7_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE8_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE9_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_OUTLINE_CODE10_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_ENTERPRISE_DATA, DataType::DT_BINARY);
	ResetTaskField(TF_PARENT_TASK_UNIQUE_ID, DataType::DT_INTEGER);
	ResetTaskField(TF_CALENDAR_UNIQUE_ID, DataType::DT_INTEGER);

	ResetTaskField(TF_FIXED_DURATION, DataType::DT_BOOLEAN);
	ResetTaskField(TF_RESUME_NO_EARLIER_THAN, DataType::DT_DATE);
	ResetTaskField(TF_PARENT_TASK, DataType::DT_INTEGER);
	ResetTaskField(TF_INDEX, DataType::DT_INTEGER);
	ResetTaskField(TF_DURATION1_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION2_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION3_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION4_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION5_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION6_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION7_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION8_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION9_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_DURATION10_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_HYPERLINK_SCREEN_TIP, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE1, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE2, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE3, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE4, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE5, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE6, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE7, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE8, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE9, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE10, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE11, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE12, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE13, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE14, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE15, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE16, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE17, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE18, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE19, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE20, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE21, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE22, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE23, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE24, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE25, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE26, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE27, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE28, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE29, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_OUTLINE_CODE30, DataType::DT_STRING);
	ResetTaskField(TF_BASELINE1_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE2_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE3_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE4_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE5_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE6_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE7_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE8_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE9_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_BASELINE10_DURATION_ESTIMATED, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST1, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST2, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST3, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST4, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST5, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST6, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST7, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST8, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST9, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_COST10, DataType::DT_CURRENCY);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE1, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE2, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE3, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE4, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE5, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE6, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE7, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE8, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE9, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE10, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE11, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE12, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE13, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE14, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE15, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE16, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE17, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE18, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE19, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE20, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE21, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE22, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE23, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE24, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE25, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE26, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE27, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE28, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE29, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DATE30, DataType::DT_DATE);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION1, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION2, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION3, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION4, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION5, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION6, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION7, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION8, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION9, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_DURATION10, DataType::DT_DURATION);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE1, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE2, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE3, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE4, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE5, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE6, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE7, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE8, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE9, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE10, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE11, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE12, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE13, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE14, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE15, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE16, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE17, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE18, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE19, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE20, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE21, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE22, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE23, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE24, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE25, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE26, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE27, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE28, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE29, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_OUTLINE_CODE30, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG1, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG2, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG3, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG4, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG5, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG6, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG7, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG8, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG9, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG10, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG11, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG12, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG13, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG14, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG15, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG16, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG17, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG18, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG19, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_FLAG20, DataType::DT_BOOLEAN);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER1, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER2, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER3, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER4, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER5, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER6, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER7, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER8, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER9, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER10, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER11, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER12, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER13, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER14, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER15, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER16, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER17, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER18, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER19, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER20, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER21, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER22, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER23, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER24, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER25, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER26, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER27, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER28, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER29, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER30, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER31, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER32, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER33, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER34, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER35, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER36, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER37, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER38, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER39, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_NUMBER40, DataType::DT_NUMERIC);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT1, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT2, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT3, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT4, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT5, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT6, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT7, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT8, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT9, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT10, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT11, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT12, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT13, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT14, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT15, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT16, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT17, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT18, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT19, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT20, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT21, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT22, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT23, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT24, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT25, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT26, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT27, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT28, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT29, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT30, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT31, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT32, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT33, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT34, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT35, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT36, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT37, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT38, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT39, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_PROJECT_TEXT40, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE1, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE2, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE3, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE4, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE5, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE6, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE7, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE8, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE9, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE10, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE11, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE12, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE13, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE14, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE15, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE16, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE17, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE18, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE19, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE20, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE21, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE22, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE23, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE24, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE25, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE26, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE27, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE28, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_OUTLINE_CODE29, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_RBS, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE20, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE21, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE22, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE23, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE24, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE25, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE26, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE27, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE28, DataType::DT_STRING);
	ResetTaskField(TF_RESOURCE_ENTERPRISE_MULTI_VALUE_CODE29, DataType::DT_STRING);
	ResetTaskField(TF_ACTUAL_WORK_PROTECTED, DataType::DT_WORK);
	ResetTaskField(TF_ACTUAL_OVERTIME_WORK_PROTECTED, DataType::DT_WORK);
	ResetTaskField(TF_BUDGET_WORK, DataType::DT_WORK);
	ResetTaskField(TF_BUDGET_COST, DataType::DT_CURRENCY);
	ResetTaskField(TF_RECALC_OUTLINE_CODES, DataType::DT_BOOLEAN);

	ResetTaskField(TF_IS_START_VALID, DataType::DT_BOOLEAN);
	ResetTaskField(TF_IS_FINISH_VALID, DataType::DT_BOOLEAN);
	ResetTaskField(TF_IS_DURATION_VALID, DataType::DT_BOOLEAN);

	ResetTaskField(TF_PATH_DRIVEN_SUCCESSOR, DataType::DT_BOOLEAN);
	ResetTaskField(TF_PATH_DRIVING_PREDECESSOR, DataType::DT_BOOLEAN);
	ResetTaskField(TF_PATH_PREDECESSOR, DataType::DT_BOOLEAN);
	ResetTaskField(TF_PATH_SUCCESSOR, DataType::DT_BOOLEAN);

	// KEEP THESE TOGETHER AND IN ORDER
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD1, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD2, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD3, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD4, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD5, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD6, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD7, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD8, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD9, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD10, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD11, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD12, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD13, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD14, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD15, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD16, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD17, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD18, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD19, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD20, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD21, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD22, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD23, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD24, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD25, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD26, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD27, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD28, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD29, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD30, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD31, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD32, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD33, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD34, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD35, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD36, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD37, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD38, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD39, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD40, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD41, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD42, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD43, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD44, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD45, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD46, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD47, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD48, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD49, DataType::DT_STRING);
	ResetTaskField(TF_ENTERPRISE_CUSTOM_FIELD50, DataType::DT_STRING);
	// KEEP THESE TOGETHER AND IN ORDER
	ResetTaskField(TF_FINISH, DataType::DT_DATE); // Must always be last value
}

FieldType* TaskFieldClass::getInstance(int type)
{
	if (type < 0)
		return NULL;

	if (_TaskFields[TF_FINISH - 1].get() == NULL)
	{
		InstanceAllTaskField();
	}

	return _TaskFields[type].get();
}